### ISSUE TITLE
missing comma in options

### ISSUE THREAD

**Issue by kdar** [insin/msx#11]
```
msx
C:\Users\kdar\AppData\Roaming\npm\node_modules\msx\bin\msx:50
    es6module: this.options.es6module,
    ^^^^^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3```

**Comment by insin** [comment]
D'oh, thanks for the report.

Fixed in 0.4.1.
